"""
Sample case records for MongoDB seeding.

This is a Python translation of the authored mock data from the frontend's
``data/mockCases.js`` and ``data/mockDashboard.js``.  Every value is sample data
written by hand for UI development — no model or parser produced any of it.

The shapes match what the frontend components expect, so the dashboard and case
workspace render identically whether reading from these seed records or the
original JS fixtures.
"""

# ---------------------------------------------------------------------------
# Severity / priority bands (mirrors ml/risk_scorer.py thresholds)
# ---------------------------------------------------------------------------

SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_HIGH = "HIGH"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_LOW = "LOW"
SEVERITY_INFO = "INFO"

# ---------------------------------------------------------------------------
# Dashboard metrics
# ---------------------------------------------------------------------------

DASHBOARD_METRICS = [
    {
        "id": "active-investigations",
        "label": "Active Investigations",
        "value": 7,
        "detail": "3 awaiting examiner review",
        "delta": {"direction": "up", "value": "+2", "period": "this week"},
    },
    {
        "id": "evidence-sources",
        "label": "Evidence Sources",
        "value": 24,
        "detail": "9 disk images · 11 log sets · 4 captures",
        "delta": {"direction": "up", "value": "+5", "period": "this week"},
    },
    {
        "id": "artifacts-analyzed",
        "label": "Artifacts Analyzed",
        "value": 1_284_907,
        "format": "compact",
        "detail": "Across all open cases",
        "delta": {"direction": "up", "value": "+184K", "period": "24h"},
    },
    {
        "id": "detected-iocs",
        "label": "Detected IOCs",
        "value": 342,
        "detail": "58 hashes · 194 addresses · 90 domains",
        "delta": {"direction": "up", "value": "+27", "period": "24h"},
    },
    {
        "id": "critical-findings",
        "label": "Critical Findings",
        "value": 19,
        "detail": "6 unreviewed on CASE-2026-0147",
        "delta": {"direction": "up", "value": "+4", "period": "24h"},
    },
]

# ---------------------------------------------------------------------------
# Recent activity
# ---------------------------------------------------------------------------

RECENT_ACTIVITY = [
    {
        "id": "A-9012",
        "kind": "finding",
        "severity": SEVERITY_CRITICAL,
        "message": "Encoded PowerShell execution flagged on FIN-WKS-014",
        "caseId": "CASE-2026-0147",
        "actor": "Triage engine",
        "relative": "4m ago",
        "at": "2026-08-26T14:28:00+05:30",
    },
    {
        "id": "A-9011",
        "kind": "ioc",
        "severity": SEVERITY_HIGH,
        "message": "3 new indicators extracted from capture-014.pcap",
        "caseId": "CASE-2026-0147",
        "actor": "Triage engine",
        "relative": "17m ago",
        "at": "2026-08-26T14:15:00+05:30",
    },
    {
        "id": "A-9010",
        "kind": "ingest",
        "severity": SEVERITY_INFO,
        "message": "Evidence source CI-AGT-009.dd verified — SHA-256 hash match",
        "caseId": "CASE-2026-0136",
        "actor": "INV-2338",
        "relative": "31m ago",
        "at": "2026-08-26T14:01:00+05:30",
    },
    {
        "id": "A-9009",
        "kind": "note",
        "severity": SEVERITY_INFO,
        "message": "Examiner note added to finding F-1044 (Registry Persistence)",
        "caseId": "CASE-2026-0147",
        "actor": "INV-2291",
        "relative": "52m ago",
        "at": "2026-08-26T13:40:00+05:30",
    },
    {
        "id": "A-9008",
        "kind": "escalation",
        "severity": SEVERITY_CRITICAL,
        "message": "CASE-2026-0139 escalated to Anti-Cyber Terrorism review",
        "caseId": "CASE-2026-0139",
        "actor": "INV-2291",
        "relative": "2h ago",
        "at": "2026-08-26T12:30:00+05:30",
    },
    {
        "id": "A-9007",
        "kind": "finding",
        "severity": SEVERITY_HIGH,
        "message": "Autorun key WinUpdateSvc correlated with unsigned binary",
        "caseId": "CASE-2026-0147",
        "actor": "Triage engine",
        "relative": "3h ago",
        "at": "2026-08-26T11:20:00+05:30",
    },
    {
        "id": "A-9006",
        "kind": "ingest",
        "severity": SEVERITY_INFO,
        "message": "5 log sets parsed from HR-LAP-072 — 213,408 artifacts scored",
        "caseId": "CASE-2026-0143",
        "actor": "Triage engine",
        "relative": "5h ago",
        "at": "2026-08-26T09:45:00+05:30",
    },
]

# ---------------------------------------------------------------------------
# Active investigations (dashboard list)
# ---------------------------------------------------------------------------

ACTIVE_INVESTIGATIONS = [
    {
        "id": "CASE-2026-0147",
        "title": "Ransomware staging on finance workstation",
        "threatScore": 87,
        "severity": SEVERITY_HIGH,
        "status": "ANALYZING",
        "progress": 68,
        "examiner": "INV-2291",
        "openedAt": "2026-08-24T09:12:00+05:30",
        "lastActivity": "4 minutes ago",
        "evidence": {"images": 2, "logSets": 5, "captures": 1},
        "artifacts": 486_112,
        "criticalFindings": 6,
        "iocHits": 41,
        "primaryHost": "FIN-WKS-014",
    },
    {
        "id": "CASE-2026-0143",
        "title": "Credential harvesting via phishing payload",
        "threatScore": 74,
        "severity": SEVERITY_HIGH,
        "status": "CORRELATING",
        "progress": 41,
        "examiner": "INV-2104",
        "openedAt": "2026-08-22T16:40:00+05:30",
        "lastActivity": "38 minutes ago",
        "evidence": {"images": 1, "logSets": 3, "captures": 2},
        "artifacts": 213_408,
        "criticalFindings": 4,
        "iocHits": 26,
        "primaryHost": "HR-LAP-072",
    },
    {
        "id": "CASE-2026-0139",
        "title": "Unauthorised database export, night shift",
        "threatScore": 91,
        "severity": SEVERITY_CRITICAL,
        "status": "ESCALATED",
        "progress": 92,
        "examiner": "INV-2291",
        "openedAt": "2026-08-19T22:05:00+05:30",
        "lastActivity": "2 hours ago",
        "evidence": {"images": 3, "logSets": 2, "captures": 1},
        "artifacts": 391_774,
        "criticalFindings": 7,
        "iocHits": 18,
        "primaryHost": "DB-PRD-002",
    },
    {
        "id": "CASE-2026-0136",
        "title": "Lateral movement across build agents",
        "threatScore": 52,
        "severity": SEVERITY_MEDIUM,
        "status": "INGESTING",
        "progress": 17,
        "examiner": "INV-2338",
        "openedAt": "2026-08-26T08:55:00+05:30",
        "lastActivity": "11 minutes ago",
        "evidence": {"images": 1, "logSets": 1, "captures": 0},
        "artifacts": 47_260,
        "criticalFindings": 1,
        "iocHits": 5,
        "primaryHost": "CI-AGT-009",
    },
]

# ---------------------------------------------------------------------------
# Triage summaries keyed by case
# ---------------------------------------------------------------------------

AI_TRIAGE_0147 = {
    "caseId": "CASE-2026-0147",
    "threatScore": 87,
    "severity": SEVERITY_HIGH,
    "confidence": 0.92,
    "modelLabel": "Isolation Forest + rule ensemble",
    "criticalFindings": 6,
    "artifactsScored": 486_112,
    "scoredAt": "2026-08-26T14:28:00+05:30",
    "recommendedAction": {
        "headline": "Isolate FIN-WKS-014 and preserve volatile memory before reboot",
        "detail": "Persistence is established and outbound C2 traffic is still active. Capture RAM and the Run-key hive, then contain the host before continuing artifact review.",
        "urgency": SEVERITY_CRITICAL,
    },
    "findings": [
        {
            "id": "F-1042",
            "title": "Suspicious PowerShell Execution",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 94,
            "confidence": 0.96,
            "source": "Security.evtx · Event 4688",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:14:37+05:30",
            "technique": {"id": "T1059.001", "name": "PowerShell"},
            "rationale": "Encoded command line with -nop -w hidden -enc, launched by a Word child process outside business hours.",
            "artifactType": "system_log",
        },
        {
            "id": "F-1043",
            "title": "Malicious File Hash",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 91,
            "confidence": 0.99,
            "source": "C:\\Users\\Public\\svc_host.exe",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:16:02+05:30",
            "technique": {"id": "T1204.002", "name": "Malicious File"},
            "rationale": "SHA-256 matches a known loader family in the local signature set. Unsigned binary written to a world-writable path.",
            "artifactType": "file",
        },
        {
            "id": "F-1044",
            "title": "Registry Persistence",
            "severity": SEVERITY_HIGH,
            "riskScore": 78,
            "confidence": 0.9,
            "source": "NTUSER.DAT · Run\\WinUpdateSvc",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:16:44+05:30",
            "technique": {"id": "T1547.001", "name": "Registry Run Keys"},
            "rationale": "Autorun value added seconds after the loader was written, pointing at the same unsigned binary.",
            "artifactType": "registry",
        },
        {
            "id": "F-1045",
            "title": "Unusual Network Connection",
            "severity": SEVERITY_HIGH,
            "riskScore": 71,
            "confidence": 0.84,
            "source": "capture-014.pcap · 45.61.x.x:8443",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:19:10+05:30",
            "technique": {"id": "T1571", "name": "Non-Standard Port"},
            "rationale": "Sustained beaconing at 60s intervals to a first-seen address; flow duration and packet rate both fall in the top 1% of the baseline.",
            "artifactType": "network",
        },
    ],
}

AI_TRIAGE_0139 = {
    "caseId": "CASE-2026-0139",
    "threatScore": 91,
    "severity": SEVERITY_CRITICAL,
    "confidence": 0.88,
    "modelLabel": "Isolation Forest + rule ensemble",
    "criticalFindings": 7,
    "artifactsScored": 391_774,
    "scoredAt": "2026-08-26T12:22:00+05:30",
    "recommendedAction": {
        "headline": "Revoke svc_reporting credentials and freeze the export job",
        "detail": "A service account exported 4.2 GB outside its baseline window. Rotate the credential, preserve the audit log, and confirm whether the archive left the network.",
        "urgency": SEVERITY_CRITICAL,
    },
    "findings": [
        {
            "id": "F-0977",
            "title": "Bulk Row Export Outside Baseline",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 96,
            "confidence": 0.94,
            "source": "audit_log · SELECT 8.4M rows",
            "host": "DB-PRD-002",
            "observedAt": "2026-08-19T23:41:12+05:30",
            "technique": {"id": "T1213", "name": "Data from Repositories"},
            "rationale": "Single query returned 340x the account\u2019s 30-day median row count, against tables it had never previously read.",
            "artifactType": "system_log",
        },
        {
            "id": "F-0978",
            "title": "Service Account Used Off-Hours",
            "severity": SEVERITY_HIGH,
            "riskScore": 81,
            "confidence": 0.86,
            "source": "Security.evtx · Event 4624 (type 3)",
            "host": "DB-PRD-002",
            "observedAt": "2026-08-19T23:38:04+05:30",
            "technique": {"id": "T1078", "name": "Valid Accounts"},
            "rationale": "Interactive-style network logon for svc_reporting at 23:38 from a workstation subnet, not the scheduler host.",
            "artifactType": "system_log",
        },
        {
            "id": "F-0979",
            "title": "Archive Staged in Temp Path",
            "severity": SEVERITY_HIGH,
            "riskScore": 76,
            "confidence": 0.91,
            "source": "D:\\Temp\\rpt_20260819.7z (4.2 GB)",
            "host": "DB-PRD-002",
            "observedAt": "2026-08-19T23:52:47+05:30",
            "technique": {"id": "T1074.001", "name": "Local Data Staging"},
            "rationale": "Compressed archive written minutes after the export, sized to match the queried tables.",
            "artifactType": "file",
        },
        {
            "id": "F-0980",
            "title": "Large Outbound Transfer",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 89,
            "confidence": 0.82,
            "source": "capture-db02.pcap · 443/tcp egress",
            "host": "DB-PRD-002",
            "observedAt": "2026-08-20T00:14:29+05:30",
            "technique": {"id": "T1048", "name": "Exfiltration Over Alt Protocol"},
            "rationale": "Sustained 4.1 GB upload to an external host; flow bytes/s in the top 0.2% of the network baseline.",
            "artifactType": "network",
        },
    ],
}

TRIAGE_BY_CASE = {
    "CASE-2026-0147": AI_TRIAGE_0147,
    "CASE-2026-0139": AI_TRIAGE_0139,
    "CASE-2026-0143": None,
    "CASE-2026-0136": None,
}

# ---------------------------------------------------------------------------
# Full case records (for the case workspace /cases/:caseId)
# ---------------------------------------------------------------------------

CASE_0147 = {
    "id": "CASE-2026-0147",
    "title": "Ransomware staging on finance workstation",
    "description": "Suspected pre-encryption ransomware staging on a Finance department workstation, opened after the endpoint team escalated an alert on encoded PowerShell. Host is still powered on and connected.",
    "threatScore": 87,
    "severity": SEVERITY_HIGH,
    "status": "ANALYZING",
    "progress": 68,
    "examiner": "INV-2291",
    "openedAt": "2026-08-24T09:12:00+05:30",
    "primaryHost": "FIN-WKS-014",
    "lastActivity": {
        "relative": "4 minutes ago",
        "at": "2026-08-26T14:28:00+05:30",
        "label": "Encoded PowerShell execution flagged",
    },
    "counts": {
        "evidence": 8,
        "artifacts": 486_112,
        "iocs": 41,
        "criticalFindings": 6,
    },
    "summary": {
        "narrative": "An encoded PowerShell command launched by a Word child process on FIN-WKS-014 at 02:14 on 24 Aug wrote an unsigned binary to a world-writable path, added a Run-key autorun pointing at it, disabled Defender real-time protection and began beaconing to 45.61.x.x:8443 at 60-second intervals. Shadow copies were deleted and a ransom note was written into two user profiles, but no bulk file encryption has been observed — the intrusion appears to have been interrupted at the staging step. Two adjacent hosts contacted the same destination and are queued for acquisition.",
        "facts": [
            {"label": "Opened", "value": "24 Aug 2026, 09:12"},
            {"label": "Examiner", "value": "INV-2291", "mono": True},
            {"label": "Primary host", "value": "FIN-WKS-014", "mono": True},
            {"label": "First observed activity", "value": "24 Aug 2026, 02:14:37"},
            {"label": "Detection lag", "value": "6 h 57 m"},
            {"label": "Hosts in scope", "value": "3"},
            {"label": "Accounts in scope", "value": "jmenon, svc_backup", "mono": True},
            {"label": "Triaged", "value": "68%"},
        ],
    },
    "assessment": {
        "scoredAt": "2026-08-26T14:28:00+05:30",
        "modelLabel": "Isolation Forest + rule ensemble",
        "confidence": 0.92,
        "composition": [
            {
                "id": "ml-anomaly",
                "label": "ML anomaly score",
                "detail": "IsolationForest decision function, normalised to 0-100",
                "score": 84.2,
                "weight": 0.6,
                "contribution": 50.5,
            },
            {
                "id": "rule-engine",
                "label": "Rule engine score",
                "detail": "9 of 14 artifact rules matched",
                "score": 91.2,
                "weight": 0.4,
                "contribution": 36.5,
            },
        ],
        "artifactPriorities": [
            {"severity": SEVERITY_CRITICAL, "count": 312},
            {"severity": SEVERITY_HIGH, "count": 1_847},
            {"severity": SEVERITY_MEDIUM, "count": 21_406},
            {"severity": SEVERITY_LOW, "count": 462_547},
        ],
        "iocBreakdown": [
            {"label": "File hashes", "count": 9},
            {"label": "IP addresses", "count": 18},
            {"label": "Domains", "count": 11},
            {"label": "Registry keys", "count": 3},
        ],
        "coverage": [
            {"tactic": "Initial Access", "state": "observed", "note": "T1566.001 · macro document"},
            {"tactic": "Execution", "state": "observed", "note": "T1059.001 · encoded PowerShell"},
            {"tactic": "Defense Evasion", "state": "observed", "note": "T1562.001 · Defender disabled"},
            {"tactic": "Persistence", "state": "observed", "note": "T1547.001 · Run key"},
            {"tactic": "Command & Control", "state": "observed", "note": "T1571 · non-standard port"},
            {"tactic": "Impact", "state": "partial", "note": "T1490 · shadow copies deleted, no encryption"},
            {"tactic": "Exfiltration", "state": "none", "note": "No outbound volume above baseline"},
        ],
    },
    "findings": [
        {
            "id": "F-1042",
            "title": "Suspicious PowerShell Execution",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 94,
            "confidence": 0.96,
            "source": "Security.evtx · Event 4688",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:14:37+05:30",
            "technique": {"id": "T1059.001", "name": "PowerShell"},
            "rationale": "Encoded command line with -nop -w hidden -enc, launched by a Word child process outside business hours.",
            "artifactType": "system_log",
            "reviewed": False,
        },
        {
            "id": "F-1043",
            "title": "Malicious File Hash",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 91,
            "confidence": 0.99,
            "source": "C:\\Users\\Public\\svc_host.exe",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:16:02+05:30",
            "technique": {"id": "T1204.002", "name": "Malicious File"},
            "rationale": "SHA-256 matches a known loader family in the local signature set. Unsigned binary written to a world-writable path.",
            "artifactType": "file",
            "reviewed": False,
        },
        {
            "id": "F-1046",
            "title": "Shadow Copy Deletion",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 89,
            "confidence": 0.95,
            "source": "Security.evtx · Event 4688 (vssadmin)",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:21:53+05:30",
            "technique": {"id": "T1490", "name": "Inhibit System Recovery"},
            "rationale": "vssadmin delete shadows /all /quiet run by the same process tree as the loader, removing the local rollback path before encryption.",
            "artifactType": "system_log",
            "reviewed": False,
        },
        {
            "id": "F-1047",
            "title": "Defender Real-Time Protection Disabled",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 86,
            "confidence": 0.93,
            "source": "SOFTWARE\\...\\Real-Time Protection\\DisableRealtimeMonitoring",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:17:26+05:30",
            "technique": {"id": "T1562.001", "name": "Disable or Modify Tools"},
            "rationale": "Policy value set to 1 by a non-administrative process 84 seconds after the loader was written; no matching change ticket.",
            "artifactType": "registry",
            "reviewed": False,
        },
        {
            "id": "F-1048",
            "title": "Ransom Note Staged in Profile Directories",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 82,
            "confidence": 0.9,
            "source": "C:\\Users\\jmenon\\Desktop\\READ_ME_RECOVER.txt",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:24:11+05:30",
            "technique": {"id": "T1486", "name": "Data Encrypted for Impact"},
            "rationale": "Identical note written to two profiles with a contact address and a wallet identifier. No encrypted file extensions present yet, which places the intrusion before the encryption step.",
            "artifactType": "file",
            "reviewed": False,
        },
        {
            "id": "F-1049",
            "title": "Archive Utility Written to Public Path",
            "severity": SEVERITY_CRITICAL,
            "riskScore": 79,
            "confidence": 0.87,
            "source": "C:\\Users\\Public\\7za.exe",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:18:40+05:30",
            "technique": {"id": "T1560.001", "name": "Archive via Utility"},
            "rationale": "Standalone archive binary dropped alongside the loader and never present in the software inventory for this host.",
            "artifactType": "file",
            "reviewed": False,
        },
        {
            "id": "F-1044",
            "title": "Registry Persistence",
            "severity": SEVERITY_HIGH,
            "riskScore": 78,
            "confidence": 0.9,
            "source": "NTUSER.DAT · Run\\WinUpdateSvc",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:16:44+05:30",
            "technique": {"id": "T1547.001", "name": "Registry Run Keys"},
            "rationale": "Autorun value added seconds after the loader was written, pointing at the same unsigned binary.",
            "artifactType": "registry",
            "reviewed": True,
        },
        {
            "id": "F-1045",
            "title": "Unusual Network Connection",
            "severity": SEVERITY_HIGH,
            "riskScore": 71,
            "confidence": 0.84,
            "source": "capture-014.pcap · 45.61.x.x:8443",
            "host": "FIN-WKS-014",
            "observedAt": "2026-08-24T02:19:10+05:30",
            "technique": {"id": "T1571", "name": "Non-Standard Port"},
            "rationale": "Sustained beaconing at 60s intervals to a first-seen address; flow duration and packet rate both fall in the top 1% of the baseline.",
            "artifactType": "network",
            "reviewed": True,
        },
    ],
    "recommendation": {
        "urgency": SEVERITY_CRITICAL,
        "headline": "Isolate FIN-WKS-014 and capture volatile memory before any reboot",
        "window": "Within 1 hour",
        "owner": "INV-2291",
        "steps": [
            "Capture RAM with a write-blocked acquisition tool while the host is still running.",
            "Export the NTUSER.DAT Run key and the Defender policy key before containment alters them.",
            "Network-isolate the host at the switch port and leave it powered on.",
            "Block 45.61.x.x:8443 at the perimeter, then sweep FIN-WKS-021 and FIN-SRV-003 for the same destination.",
        ],
        "rationale": "Persistence is established and the beacon is still answering, so the operator can act on the host at any time. Shadow copies are already deleted and a ransom note is staged, which puts the intrusion one step short of encryption. A reboot or a power-off destroys the loader configuration and any key material that exists only in memory, and a second host contacting the same destination indicates more than one foothold — containing this workstation alone would leave the intrusion live.",
    },
    "activity": [
        {"id": "A-9012", "kind": "finding", "severity": SEVERITY_CRITICAL, "message": "Encoded PowerShell execution flagged on FIN-WKS-014", "caseId": "CASE-2026-0147", "actor": "Triage engine", "relative": "4m ago", "at": "2026-08-26T14:28:00+05:30"},
        {"id": "A-9011", "kind": "ioc", "severity": SEVERITY_HIGH, "message": "3 new indicators extracted from capture-014.pcap", "caseId": "CASE-2026-0147", "actor": "Triage engine", "relative": "17m ago", "at": "2026-08-26T14:15:00+05:30"},
        {"id": "A-9009", "kind": "note", "severity": SEVERITY_INFO, "message": "Examiner note added to finding F-1044 (Registry Persistence)", "caseId": "CASE-2026-0147", "actor": "INV-2291", "relative": "52m ago", "at": "2026-08-26T13:40:00+05:30"},
        {"id": "A-9007", "kind": "finding", "severity": SEVERITY_HIGH, "message": "Autorun key WinUpdateSvc correlated with unsigned binary", "caseId": "CASE-2026-0147", "actor": "Triage engine", "relative": "3h ago", "at": "2026-08-26T11:20:00+05:30"},
        {"id": "A-9004", "kind": "finding", "severity": SEVERITY_CRITICAL, "message": "Shadow copy deletion detected via vssadmin (F-1046)", "caseId": "CASE-2026-0147", "actor": "Triage engine", "relative": "5h ago", "at": "2026-08-26T09:35:00+05:30"},
        {"id": "A-9002", "kind": "ingest", "severity": SEVERITY_INFO, "message": "Evidence source FIN-WKS-014-D.e01 verified — SHA-256 hash match", "caseId": "CASE-2026-0147", "actor": "INV-2291", "relative": "8h ago", "at": "2026-08-26T06:50:00+05:30"},
        {"id": "A-9001", "kind": "ingest", "severity": SEVERITY_INFO, "message": "Case opened and evidence intake started", "caseId": "CASE-2026-0147", "actor": "INV-2291", "relative": "2d ago", "at": "2026-08-24T09:12:00+05:30"},
    ],
    "evidence": {
        "sources": [
            {"id": "EV-0147-01", "label": "FIN-WKS-014-C.e01", "kind": "image", "detail": "C: system volume", "size": "476 GB", "acquiredAt": "2026-08-24T10:02:00+05:30", "custodian": "INV-2291", "sha256": "4f2c9a7d1b8e0c356af91d2e7c48b60539ea1f7c2d6b485901ac3e7f9d21b846", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-02", "label": "FIN-WKS-014-D.e01", "kind": "image", "detail": "D: data volume", "size": "931 GB", "acquiredAt": "2026-08-24T13:41:00+05:30", "custodian": "INV-2291", "sha256": "8b1e05c73d29af640c58b1e792da4f0361c7e8b24a0d9f357e2b16c805d3a94f", "integrity": "HASH MATCH", "state": "INDEXING"},
            {"id": "EV-0147-03", "label": "Security.evtx", "kind": "log", "detail": "Windows Security log", "size": "84 MB", "acquiredAt": "2026-08-24T10:18:00+05:30", "custodian": "INV-2291", "sha256": "c05a37f91e6b48d20937ac5eb8d10f642c9e75a34f08b1d763ea2c908d5f7b14", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-04", "label": "System.evtx", "kind": "log", "detail": "Windows System log", "size": "41 MB", "acquiredAt": "2026-08-24T10:18:00+05:30", "custodian": "INV-2291", "sha256": "1d74b0e95a2c8f3607be91d4c3620ad89f15e7b246c0d38a71eb5f290c84a6d3", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-05", "label": "PowerShell%4Operational.evtx", "kind": "log", "detail": "PowerShell operational log", "size": "22 MB", "acquiredAt": "2026-08-24T10:19:00+05:30", "custodian": "INV-2291", "sha256": "96ef2a08b4d75c132f80e6a917cb43d58a02f9e63d61b48c0e57a2fbd914630a", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-06", "label": "NTUSER.DAT (jmenon)", "kind": "registry", "detail": "User registry hive", "size": "12 MB", "acquiredAt": "2026-08-24T10:24:00+05:30", "custodian": "INV-2291", "sha256": "3a8d0169c72fb4e59d03a86b145ef0c728b9d43a6f01c25eb7a48d9053c6e1fb", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-07", "label": "edge-proxy-20260824.log", "kind": "log", "detail": "Perimeter proxy log, 24 Aug", "size": "318 MB", "acquiredAt": "2026-08-25T09:05:00+05:30", "custodian": "INV-2338", "sha256": "7e14c3b08f2a95d601db47eca35208f96c8e1b47d90f5a232b76c0e84159da3c", "integrity": "HASH MATCH", "state": "PARSED"},
            {"id": "EV-0147-08", "label": "capture-014.pcap", "kind": "capture", "detail": "Span capture, FIN VLAN", "size": "1.4 GB", "acquiredAt": "2026-08-25T11:30:00+05:30", "custodian": "INV-2338", "sha256": "d2039f7a65be18c40a7d532fe91c60b8374af0d91e8b25c6c0956d138b4f27ea", "integrity": "HASH MATCH", "state": "PARSED"},
        ],
        "pending": [
            {"id": "EV-0147-P1", "label": "Volatile memory (FIN-WKS-014)", "reason": "Host still powered on — required before containment, see the recommendation above"},
            {"id": "EV-0147-P2", "label": "Disk image (FIN-WKS-021)", "reason": "Second host contacted the same C2 destination; acquisition not started"},
        ],
    },
}

CASE_0143 = {
    "id": "CASE-2026-0143",
    "title": "Credential harvesting via phishing payload",
    "description": "HTML phishing attachment impersonating the company portal captured O365 credentials. Two accounts in HR confirmed compromised.",
    "threatScore": 74,
    "severity": SEVERITY_HIGH,
    "status": "CORRELATING",
    "progress": 41,
    "examiner": "INV-2104",
    "openedAt": "2026-08-22T16:40:00+05:30",
    "primaryHost": "HR-LAP-072",
    "lastActivity": {
        "relative": "38 minutes ago",
        "at": "2026-08-26T13:54:00+05:30",
        "label": "Correlation run started across HR log sets",
    },
    "counts": {
        "evidence": 6,
        "artifacts": 213_408,
        "iocs": 26,
        "criticalFindings": 4,
    },
    "summary": {
        "narrative": "An HTML attachment posing as the company SSO portal was opened on HR-LAP-072, capturing the credentials for two HR accounts. A follow-up sign-in from an external IP used one account to access the shared HR drive and download 14 documents containing PII. The second account was used to forward 47 messages from the inbox to an external address. Both sessions originated from the same VPN egress IP within minutes of each other.",
        "facts": [
            {"label": "Opened", "value": "22 Aug 2026, 16:40"},
            {"label": "Examiner", "value": "INV-2104", "mono": True},
            {"label": "Primary host", "value": "HR-LAP-072", "mono": True},
            {"label": "Accounts compromised", "value": "2"},
            {"label": "Triaged", "value": "41%"},
        ],
    },
    "assessment": None,
    "findings": [],
    "recommendation": {
        "urgency": SEVERITY_HIGH,
        "headline": "Reset credentials for the two compromised HR accounts",
        "window": "Immediately",
        "owner": "INV-2104",
        "steps": [
            "Force password reset and revoke active sessions for both HR accounts.",
            "Enable MFA on both accounts if not already active.",
            "Review the 14 downloaded documents for PII exposure scope.",
            "Block the external VPN egress IP at the perimeter.",
        ],
        "rationale": "The attacker still has valid credentials and has already accessed PII. Credential reset is the minimum action to stop further access.",
    },
    "activity": [
        {"id": "A-9006", "kind": "ingest", "severity": SEVERITY_INFO, "message": "5 log sets parsed from HR-LAP-072 — 213,408 artifacts scored", "caseId": "CASE-2026-0143", "actor": "Triage engine", "relative": "5h ago", "at": "2026-08-26T09:45:00+05:30"},
    ],
    "evidence": {
        "sources": [
            {"id": "EV-0143-01", "label": "HR-LAP-072.e01", "kind": "image", "detail": "System volume", "size": "256 GB", "acquiredAt": "2026-08-22T18:15:00+05:30", "custodian": "INV-2104", "sha256": "ab12cd34ef56ab12cd34ef56ab12cd34ef56ab12cd34ef56ab12cd34ef56ab12", "integrity": "HASH MATCH", "state": "PARSED"},
        ],
        "pending": [],
    },
}

CASE_0139 = {
    "id": "CASE-2026-0139",
    "title": "Unauthorised database export, night shift",
    "description": "A reporting service account exported 8.4 million rows from production outside its baseline window and staged a compressed archive locally. Escalated to Anti-Cyber Terrorism review.",
    "threatScore": 91,
    "severity": SEVERITY_CRITICAL,
    "status": "ESCALATED",
    "progress": 92,
    "examiner": "INV-2291",
    "openedAt": "2026-08-19T22:05:00+05:30",
    "primaryHost": "DB-PRD-002",
    "lastActivity": {
        "relative": "2 hours ago",
        "at": "2026-08-26T12:30:00+05:30",
        "label": "Escalated to Anti-Cyber Terrorism review",
    },
    "counts": {
        "evidence": 6,
        "artifacts": 391_774,
        "iocs": 18,
        "criticalFindings": 7,
    },
    "summary": {
        "narrative": "The svc_reporting account signed in from a workstation subnet at 23:38 on 19 Aug, was granted sysadmin minutes later, and ran a single query returning 8.4 million rows against tables it had never previously read. A 4.2 GB archive was written to D:\\Temp and a sustained 4.1 GB upload left the host over 443/tcp shortly after midnight. Audit rows covering the export window were then deleted and backup retention was cut from 35 days to 1. The account owner has confirmed they did not schedule the job.",
        "facts": [
            {"label": "Opened", "value": "19 Aug 2026, 22:05"},
            {"label": "Examiner", "value": "INV-2291", "mono": True},
            {"label": "Primary host", "value": "DB-PRD-002", "mono": True},
            {"label": "First observed activity", "value": "19 Aug 2026, 23:38:04"},
            {"label": "Detection lag", "value": "22 h 27 m"},
            {"label": "Hosts in scope", "value": "2"},
            {"label": "Accounts in scope", "value": "svc_reporting", "mono": True},
            {"label": "Triaged", "value": "92%"},
        ],
    },
    "assessment": {
        "scoredAt": "2026-08-26T12:22:00+05:30",
        "modelLabel": "Isolation Forest + rule ensemble",
        "confidence": 0.88,
        "composition": [
            {"id": "ml-anomaly", "label": "ML anomaly score", "detail": "IsolationForest decision function, normalised to 0-100", "score": 88.5, "weight": 0.6, "contribution": 53.1},
            {"id": "rule-engine", "label": "Rule engine score", "detail": "11 of 14 artifact rules matched", "score": 94.75, "weight": 0.4, "contribution": 37.9},
        ],
        "artifactPriorities": [
            {"severity": SEVERITY_CRITICAL, "count": 604},
            {"severity": SEVERITY_HIGH, "count": 3_118},
            {"severity": SEVERITY_MEDIUM, "count": 34_902},
            {"severity": SEVERITY_LOW, "count": 353_150},
        ],
        "iocBreakdown": [
            {"label": "File hashes", "count": 3},
            {"label": "IP addresses", "count": 9},
            {"label": "Domains", "count": 5},
            {"label": "Registry keys", "count": 1},
        ],
        "coverage": [
            {"tactic": "Initial Access", "state": "partial", "note": "Valid account used, entry vector unresolved"},
            {"tactic": "Privilege Escalation", "state": "observed", "note": "T1098 · sysadmin granted"},
            {"tactic": "Defense Evasion", "state": "observed", "note": "T1070 · audit rows deleted"},
            {"tactic": "Persistence", "state": "observed", "note": "T1053.005 · scheduled job created"},
            {"tactic": "Collection", "state": "observed", "note": "T1213 · bulk row export"},
            {"tactic": "Exfiltration", "state": "observed", "note": "T1048 · 4.1 GB egress"},
            {"tactic": "Impact", "state": "partial", "note": "T1490 · retention shortened, no data loss yet"},
        ],
    },
    "findings": [
        {"id": "F-0977", "title": "Bulk Row Export Outside Baseline", "severity": SEVERITY_CRITICAL, "riskScore": 96, "confidence": 0.94, "source": "audit_log · SELECT 8.4M rows", "host": "DB-PRD-002", "observedAt": "2026-08-19T23:41:12+05:30", "technique": {"id": "T1213", "name": "Data from Repositories"}, "rationale": "Single query returned 340x the account\u2019s 30-day median row count, against tables it had never previously read.", "artifactType": "system_log", "reviewed": True},
        {"id": "F-0980", "title": "Large Outbound Transfer", "severity": SEVERITY_CRITICAL, "riskScore": 89, "confidence": 0.82, "source": "capture-db02.pcap · 443/tcp egress", "host": "DB-PRD-002", "observedAt": "2026-08-20T00:14:29+05:30", "technique": {"id": "T1048", "name": "Exfiltration Over Alt Protocol"}, "rationale": "Sustained 4.1 GB upload to an external host; flow bytes/s in the top 0.2% of the network baseline.", "artifactType": "network", "reviewed": True},
        {"id": "F-0981", "title": "Audit Rows Deleted After Export", "severity": SEVERITY_CRITICAL, "riskScore": 87, "confidence": 0.91, "source": "audit_log · 11,204 rows removed", "host": "DB-PRD-002", "observedAt": "2026-08-20T00:31:08+05:30", "technique": {"id": "T1070", "name": "Indicator Removal"}, "rationale": "Deleted range covers exactly the export window. Sequence gap confirmed against the offline audit copy.", "artifactType": "system_log", "reviewed": False},
        {"id": "F-0982", "title": "Linked Server Added to External Host", "severity": SEVERITY_CRITICAL, "riskScore": 84, "confidence": 0.86, "source": "sys.servers · EXTRPT01", "host": "DB-PRD-002", "observedAt": "2026-08-19T23:52:03+05:30", "technique": {"id": "T1505.001", "name": "SQL Stored Procedures"}, "rationale": "Linked server created pointing outside the datacentre range, with no corresponding change record.", "artifactType": "system_log", "reviewed": False},
        {"id": "F-0984", "title": "Privileged Role Granted to Service Account", "severity": SEVERITY_CRITICAL, "riskScore": 82, "confidence": 0.93, "source": "audit_log · ALTER SERVER ROLE sysadmin", "host": "DB-PRD-002", "observedAt": "2026-08-19T23:39:47+05:30", "technique": {"id": "T1098", "name": "Account Manipulation"}, "rationale": "svc_reporting was added to sysadmin 103 seconds after logon; the account had held read-only rights for the previous 14 months.", "artifactType": "system_log", "reviewed": False},
        {"id": "F-0983", "title": "Backup Retention Shortened", "severity": SEVERITY_CRITICAL, "riskScore": 79, "confidence": 0.88, "source": "msdb.backupset · retention 35d -> 1d", "host": "DB-PRD-002", "observedAt": "2026-08-20T00:33:52+05:30", "technique": {"id": "T1490", "name": "Inhibit System Recovery"}, "rationale": "Retention policy reduced immediately after the audit deletion, which would have aged out the remaining evidence within a day.", "artifactType": "system_log", "reviewed": False},
        {"id": "F-0985", "title": "Off-Hours Scheduled Job Created", "severity": SEVERITY_CRITICAL, "riskScore": 77, "confidence": 0.85, "source": "msdb.sysjobs · rpt_nightly_v2", "host": "DB-PRD-002", "observedAt": "2026-08-20T00:36:19+05:30", "technique": {"id": "T1053.005", "name": "Scheduled Task/Job"}, "rationale": "New job duplicates the export query on a nightly schedule, owned by svc_reporting and disabled but not deleted.", "artifactType": "system_log", "reviewed": False},
        {"id": "F-0978", "title": "Service Account Used Off-Hours", "severity": SEVERITY_HIGH, "riskScore": 81, "confidence": 0.86, "source": "Security.evtx · Event 4624 (type 3)", "host": "DB-PRD-002", "observedAt": "2026-08-19T23:38:04+05:30", "technique": {"id": "T1078", "name": "Valid Accounts"}, "rationale": "Interactive-style network logon for svc_reporting at 23:38 from a workstation subnet, not the scheduler host.", "artifactType": "system_log", "reviewed": True},
        {"id": "F-0979", "title": "Archive Staged in Temp Path", "severity": SEVERITY_HIGH, "riskScore": 76, "confidence": 0.91, "source": "D:\\Temp\\rpt_20260819.7z (4.2 GB)", "host": "DB-PRD-002", "observedAt": "2026-08-19T23:52:47+05:30", "technique": {"id": "T1074.001", "name": "Local Data Staging"}, "rationale": "Compressed archive written minutes after the export, sized to match the queried tables.", "artifactType": "file", "reviewed": True},
    ],
    "recommendation": {
        "urgency": SEVERITY_CRITICAL,
        "headline": "Revoke svc_reporting credentials and freeze the export job",
        "window": "Immediately",
        "owner": "INV-2291",
        "steps": [
            "Rotate the svc_reporting credential and remove it from sysadmin.",
            "Disable the rpt_nightly_v2 job and drop the EXTRPT01 linked server after imaging the msdb metadata.",
            "Restore backup retention to 35 days and preserve the offline audit copy covering 19-20 Aug.",
            "Confirm with the network team whether the 4.1 GB upload completed, and to which destination.",
        ],
        "rationale": "The account still holds sysadmin and a scheduled job would repeat the export on its next run, so the same access remains available tonight. Audit rows were deleted and backup retention was cut to a single day, which gives the remaining evidence a short shelf life — restoring retention has to happen before anything else ages out. Whether this becomes a confirmed data breach depends entirely on whether the upload completed, so that answer also determines the notification obligations.",
    },
    "activity": [
        {"id": "A-9008", "kind": "escalation", "severity": SEVERITY_CRITICAL, "message": "CASE-2026-0139 escalated to Anti-Cyber Terrorism review", "caseId": "CASE-2026-0139", "actor": "INV-2291", "relative": "2h ago", "at": "2026-08-26T12:30:00+05:30"},
        {"id": "A-8998", "kind": "finding", "severity": SEVERITY_CRITICAL, "message": "Audit row deletion confirmed against the offline audit copy", "caseId": "CASE-2026-0139", "actor": "Triage engine", "relative": "4h ago", "at": "2026-08-26T10:12:00+05:30"},
        {"id": "A-8996", "kind": "note", "severity": SEVERITY_INFO, "message": "Account owner statement recorded — job was not scheduled by them", "caseId": "CASE-2026-0139", "actor": "INV-2291", "relative": "6h ago", "at": "2026-08-26T08:40:00+05:30"},
    ],
    "evidence": {
        "sources": [
            {"id": "EV-0139-01", "label": "DB-PRD-002-sys.e01", "kind": "image", "detail": "System volume", "size": "240 GB", "acquiredAt": "2026-08-20T14:20:00+05:30", "custodian": "INV-2104", "sha256": "5c8b02e1a4f7361d09e2c5b87d13fa04b6280c9e31d5a7f24e0bc86392af14d7", "integrity": "HASH MATCH", "state": "PARSED"},
        ],
        "pending": [],
    },
}

CASE_0136 = {
    "id": "CASE-2026-0136",
    "title": "Lateral movement across build agents",
    "description": "PSExec-style lateral movement detected across CI build agents. Source host is CI-AGT-009. Investigation is in early ingestion phase.",
    "threatScore": 52,
    "severity": SEVERITY_MEDIUM,
    "status": "INGESTING",
    "progress": 17,
    "examiner": "INV-2338",
    "openedAt": "2026-08-26T08:55:00+05:30",
    "primaryHost": "CI-AGT-009",
    "lastActivity": {
        "relative": "11 minutes ago",
        "at": "2026-08-26T14:21:00+05:30",
        "label": "Evidence source CI-AGT-009.dd verified",
    },
    "counts": {
        "evidence": 2,
        "artifacts": 47_260,
        "iocs": 5,
        "criticalFindings": 1,
    },
    "summary": {
        "narrative": "PSExec-style remote execution detected from CI-AGT-009 to three adjacent build agents. The source host ran a batch script that copied a service binary to each target and started it via the SCM. All activity occurred within a 4-minute window during a scheduled maintenance period, which initially masked the behaviour. The ingested disk image is being indexed.",
        "facts": [
            {"label": "Opened", "value": "26 Aug 2026, 08:55"},
            {"label": "Examiner", "value": "INV-2338", "mono": True},
            {"label": "Primary host", "value": "CI-AGT-009", "mono": True},
            {"label": "Triaged", "value": "17%"},
        ],
    },
    "assessment": None,
    "findings": [],
    "recommendation": {
        "urgency": SEVERITY_MEDIUM,
        "headline": "Complete evidence ingestion before scoping containment",
        "window": "Within 4 hours",
        "owner": "INV-2338",
        "steps": [
            "Wait for disk image indexing to complete.",
            "Review the batch script and service binary for IOC matching.",
            "Determine if the lateral movement was authorised maintenance.",
        ],
        "rationale": "The activity overlapped with a scheduled maintenance window so it may be benign. Full indexing is needed before a containment decision.",
    },
    "activity": [
        {"id": "A-9010", "kind": "ingest", "severity": SEVERITY_INFO, "message": "Evidence source CI-AGT-009.dd verified — SHA-256 hash match", "caseId": "CASE-2026-0136", "actor": "INV-2338", "relative": "31m ago", "at": "2026-08-26T14:01:00+05:30"},
    ],
    "evidence": {
        "sources": [
            {"id": "EV-0136-01", "label": "CI-AGT-009.dd", "kind": "image", "detail": "Raw disk image", "size": "128 GB", "acquiredAt": "2026-08-26T09:30:00+05:30", "custodian": "INV-2338", "sha256": "ef01234567890abcdef01234567890abcdef01234567890abcdef01234567890a", "integrity": "HASH MATCH", "state": "INDEXING"},
        ],
        "pending": [
            {"id": "EV-0136-P1", "label": "Disk images (CI-AGT-010, -011, -012)", "reason": "Three target hosts pending acquisition approval"},
        ],
    },
}

# List used by seed_if_empty()
SAMPLE_CASES = [CASE_0147, CASE_0143, CASE_0139, CASE_0136]
